In [1]:
import numpy as np

# 1D array

In [3]:
print(arr1)

[1 2 3 4 5]


In [2]:
arr1=np.array([1,2,3,4,5])

In [4]:
type(arr1)

numpy.ndarray

In [7]:
print("the first element",arr1[0])
print("the last element",arr1[-1])

the first element 1
the last element 5


In [8]:
arr1[0:3:1]

array([1, 2, 3])

In [9]:
arr1[1:5:2]

array([2, 4])

# 2D array

In [10]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr2.ndim #dimention

2

In [14]:
arr2.shape #no of rows and columns

(3, 3)

In [15]:
arr2.size #n*m #no of elemts

9

# Null Matrix/zero matrix

In [16]:
#3*3 --> all elemts as 0
#np.arr([[0,0,0],[0,0,0],[0,0,0]])

In [17]:
zero_array=np.zeros((5,5),dtype=int) #bydefault all elemts data types is float

In [18]:
print(zero_array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# Ones matrix

In [19]:
ones_array=np.ones((5,5),dtype=int)
print(ones_array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [20]:
ones_array=np.ones((7,5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Full Matrix

In [24]:
full_matrix=np.full((3,5),fill_value=7)
print(full_matrix)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [26]:
full_matrix=np.full((5,5),fill_value="S")
print(full_matrix)

[['S' 'S' 'S' 'S' 'S']
 ['S' 'S' 'S' 'S' 'S']
 ['S' 'S' 'S' 'S' 'S']
 ['S' 'S' 'S' 'S' 'S']
 ['S' 'S' 'S' 'S' 'S']]


# Identity Matrix

In [27]:
#diagonal elents as 1 #it is always square matrix[rows=colums]

In [28]:
np.eye(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

# arange function

In [ ]:
range(0,10)-->[0,1,2,3,4,5,6,7,8,9]
range(0,10,2)-->[0,2,4,6,8]

In [31]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape 

In [33]:
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
arr.size

10

In [37]:
reshaped_arr=arr.reshape(2,5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
reshaped_arr2=arr.reshape(2,7) #cannot reshape array of size 10 into shape (2,7)
reshaped_arr2

ValueError: cannot reshape array of size 10 into shape (2,7)

# Transpose Matrix

In [47]:
arr=np.array([[1,2,4],[5,0,8],[8,0,15]])
print(arr)
print(arr.shape)

[[ 1  2  4]
 [ 5  0  8]
 [ 8  0 15]]
(3, 3)


In [48]:
transposed_array=np.transpose(arr)

In [49]:
print(transposed_array)
print(transposed_array.shape)

[[ 1  5  8]
 [ 2  0  0]
 [ 4  8 15]]
(3, 3)


# Mathematical Operations

In [103]:
x=np.array([[1,2,3],[6,7,9],[3,5,7]])
y=np.array([[8,9,7],[1,5,7],[5,6,3]])

In [104]:
x+y

array([[ 9, 11, 10],
       [ 7, 12, 16],
       [ 8, 11, 10]])

In [105]:
np.add(x,y)

array([[ 9, 11, 10],
       [ 7, 12, 16],
       [ 8, 11, 10]])

In [106]:
x-y

array([[-7, -7, -4],
       [ 5,  2,  2],
       [-2, -1,  4]])

In [107]:
np.subtract(x,y)

array([[-7, -7, -4],
       [ 5,  2,  2],
       [-2, -1,  4]])

In [108]:
np.multiply(x,y)

array([[ 8, 18, 21],
       [ 6, 35, 63],
       [15, 30, 21]])

In [109]:
np.divide(x,y)
np.round(np.divide(x,y),2)

array([[0.12, 0.22, 0.43],
       [6.  , 1.4 , 1.29],
       [0.6 , 0.83, 2.33]])

In [112]:
# Element-wise multiplication
x*y

array([[ 8, 18, 21],
       [ 6, 35, 63],
       [15, 30, 21]])

In [113]:
#Matrix multiplication 
x@y

array([[ 25,  37,  30],
       [100, 143, 118],
       [ 64,  94,  77]])

In [111]:
np.matmul(x,y)

array([[ 25,  37,  30],
       [100, 143, 118],
       [ 64,  94,  77]])

In [64]:
#quiz
data=np.array([[1,2,3],
              [2,3,5],
              [4,5,8]])

In [65]:
middle_col=data[:,1]
middle_col

array([2, 3, 5])

In [79]:
n=int(input())
arr=np.zeros((n,n),dtype=int)
arr[0]=1
arr[-1]=1
arr[:,0]=1
arr[:,-1]=1
print(arr)

5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [78]:
n=int(input())
arr = np.ones((n,n),dtype=int) 
arr[1:-1,1:-1]=0 
print(arr)

4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


# Flatten array-2d to 1d

In [69]:
arr=np.array([[1,2,3],[6,7,9],[3,5,7]])
arr

array([[1, 2, 3],
       [6, 7, 9],
       [3, 5, 7]])

In [71]:
flattened_array=arr.flatten()
flattened_array

array([1, 2, 3, 6, 7, 9, 3, 5, 7])

# stacking

In [72]:
x

array([[1, 2, 3],
       [6, 7, 9],
       [3, 5, 7]])

In [73]:
y

array([[8, 9, 0],
       [1, 5, 7],
       [5, 6, 3]])

In [76]:
vertical_stack=np.vstack((x,y)) #top &bottom #no of cols shoul be same
vertical_stack

array([[1, 2, 3],
       [6, 7, 9],
       [3, 5, 7],
       [8, 9, 0],
       [1, 5, 7],
       [5, 6, 3]])

In [77]:
horizontal_stack=np.hstack((x,y)) #side by side #no of rows should be same
horizontal_stack

array([[1, 2, 3, 8, 9, 0],
       [6, 7, 9, 1, 5, 7],
       [3, 5, 7, 5, 6, 3]])

In [100]:
identity_matrix=np.eye(3,dtype=int)
vertical_stacked=np.vstack((identity_matrix,identity_matrix,identity_matrix))
horizontal_stacked=np.hstack((identity_matrix,identity_matrix,identity_matrix))
print(identity_matrix)
print("-------------------")
print(vertical_stacked)
print("-------------------")
print(horizontal_stacked)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
-------------------
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
-------------------
[[1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]]


In [84]:
x = y = np.eye(3, dtype = int) 
np.vstack((x,y)) 
np.hstack((x,y))

array([[1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1]])

In [99]:
#Create a NumPy array of size 5x5 with random integers ranging from 1 to 10.
array=np.random.randint(1,11,size=(5,5)) 
array

array([[ 1,  5,  5,  8, 10],
       [ 4,  8,  9,  5,  4],
       [ 6,  7,  5,  2,  6],
       [ 5,  6, 10,  4,  9],
       [ 7,  1, 10,  6,  8]])

In [90]:
array=np.round(np.random.rand(5,5),2)
array

array([[0.52, 0.24, 0.26, 0.24, 0.98],
       [0.11, 0.03, 0.46, 0.45, 0.62],
       [0.3 , 0.48, 0.43, 0.12, 0.79],
       [0.62, 0.34, 0.58, 0.95, 0.66],
       [0.52, 0.23, 0.89, 0.34, 0.33]])

In [98]:
arr1=np.random.rand(4,4)
arr2=np.random.rand(4,4)
res1=arr1*arr2
res2=arr1@arr2
print(res1)
print(res2)

[[0.48793644 0.03064909 0.19349365 0.22868497]
 [0.51794434 0.04007633 0.69647022 0.07458562]
 [0.32539946 0.17632725 0.36222982 0.04778682]
 [0.3946762  0.08969594 0.26393181 0.42963403]]
[[1.12756338 0.6145225  1.22945821 0.95466133]
 [1.27321804 1.03213926 1.69893091 0.99495034]
 [0.81763722 0.60542714 1.13542816 0.49801582]
 [1.42291481 1.02507875 1.83997621 1.0729674 ]]


In [92]:
#given an array, reverse the row
data=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [93]:
np.flip(data,axis=0) #row wise flip

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [94]:
np.flip(data,axis=1)#cloumn wise

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [96]:
np.flip(data)#overall flip

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [97]:
# Quiz: Given a NumPy array arr, calculate the mean and max of its elements.
arr = np.array([1, 2, 3, 4, 5])
print("Sum",np.sum(arr))
print("Max",np.max(arr))
print("Min",np.min(arr))
print("Mean",np.mean(arr))
print("Median",np.median(arr))

Sum 15
Max 5
Min 1
Mean 3.0
Median 3.0
